on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: pkishorez/vercel-preview-url@v0.0.7
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          projectId: prj_o0Yr85BNzA5TrXNhcN0GkkwXNEcB
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The Deployment URL was ${{ steps.hello.outputs.vercelDeploymentUrl }}"
